# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1meUpey4Y0jACD0MQYHuRBH4wWv84tPCZ
"""

!pip install -q -U torch transformers peft datasets==2.19.2 trl accelerate

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

# Görseldeki Model ID'si
model_id = "Qwen/Qwen2.5-Coder-1.5B-Instruct"

print(f"{model_id} modeli bfloat16 formatında yükleniyor...")

# Modeli Yükleme (Quantization olmadan)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype=torch.bfloat16,       # L4 GPU için en verimli ve kararlı format
    device_map="auto"           # Otomatik olarak GPU'ya yerleştir
)

# Tokenizer Yükleme
tokenizer = AutoTokenizer.from_pretrained(model_id)

# Qwen modellerinde bazen pad_token tanımlı gelmeyebiliyor,
# eğitimde hata almamak için eos_token'ı pad_token olarak atıyoruz.
tokenizer.pad_token = tokenizer.eos_token

model.config.use_cache = False

print("Model ve Tokenizer (Quantization olmadan) başarıyla yüklendi!")

# 3. Model Testi (Inference)

# Sormak istediğin soru
prompt = "Prepare a code to sum two input value."

# Modeli sohbet formatına hazırlama (Qwen prompt şablonunu uygular)
messages = [
    {"role": "system", "content": "You are an expert Python programmer. Please read the problem carefully before wr1t1ng any Python code."},
    {"role": "user", "content": prompt}
]

# Promptu modelin anlayacağı formata (token) çevirme
text = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)
model_inputs = tokenizer([text], return_tensors="pt").to(model.device)

print("Cevap üretiliyor...\n" + "-"*30)

# Cevabı üretme
generated_ids = model.generate(
    **model_inputs,
    max_new_tokens=512,  # Cevabın uzunluk limiti
    do_sample=True,      # Yaratıcı üretim için (False yaparsan hep aynı cevabı verir)
    temperature=0.7      # Yaratıcılık katsayısı
)

# Sadece üretilen yeni kısmı alıp yazıya çevirme (decode)
generated_ids = [
    output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
]
response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]

print(response)

from datasets import load_dataset

# -------------------------------------------------
# 1. Dataset Yükleme
# -------------------------------------------------

dataset_name = "Naholav/CodeGen-Deep-5K"
print(f"{dataset_name} indiriliyor...")

# Dataset sadece train split içeriyor
full_dataset = load_dataset(dataset_name, split="train")

print(f"Toplam Veri: {len(full_dataset)}")

# -------------------------------------------------
# 2. Train / Validation / Test Bölme (80 / 10 / 10)
# -------------------------------------------------

# Önce %80 Train, %20 Temp (Val + Test)
split_1 = full_dataset.train_test_split(
    test_size=0.2,
    seed=42
)

train_dataset = split_1["train"]   # %80
temp_dataset  = split_1["test"]    # %20

# Temp'i %10 Validation + %10 Test olarak böl
split_2 = temp_dataset.train_test_split(
    test_size=0.5,
    seed=42
)

val_dataset  = split_2["train"]    # %10
test_dataset = split_2["test"]     # %10

print(f"Eğitim (Train): {len(train_dataset)}")
print(f"Doğrulama (Validation): {len(val_dataset)}")
print(f"Test: {len(test_dataset)}")

# -------------------------------------------------
# 3. INSTRUCTION FORMATLAMA
# -------------------------------------------------

def format_instruction(sample):
    """
    Dataset'i Qwen / Instruct SFT formatına çevirir.
    SADECE input + solution kullanılır.
    """
    return {
        "text": (
            "### Instruction:\n"
            f"{sample['input']}\n\n"
            "### Response:\n"
            f"{sample['solution']}"
        )
    }

print("Dataset formatlanıyor...")

# Eski sütunları SİLEREK map ediyoruz
train_dataset = train_dataset.map(
    format_instruction,
    remove_columns=train_dataset.column_names
)

val_dataset = val_dataset.map(
    format_instruction,
    remove_columns=val_dataset.column_names
)

test_dataset = test_dataset.map(
    format_instruction,
    remove_columns=test_dataset.column_names
)

# 4. KONTROL
# -------------------------------------------------

print("\n--- İŞLENMİŞ TRAIN ÖRNEĞİ ---")
print(train_dataset[0]["text"])

from peft import LoraConfig, get_peft_model, TaskType

# 5. LoRA Konfigürasyonu (Eğitim Ayarları)

peft_config = LoraConfig(
    r=16,           # Rank: Eğitilecek parametrelerin boyutu. (8, 16, 32, 64 kullanılır. 16 iyi bir başlangıçtır.)
    lora_alpha=32,  # Alpha: Öğrenme katsayısı (Genelde r'nin 2 katı seçilir).
    target_modules=[
        "q_proj", "k_proj", "v_proj", "o_proj", # Attention katmanları
        "gate_proj", "up_proj", "down_proj"     # MLP katmanları
    ], # Qwen modelindeki tüm lineer katmanları hedefliyoruz (En iyi performans için).
    lora_dropout=0.05, # Aşırı öğrenmeyi (overfitting) engellemek için rastgele nöron kapatma oranı.
    bias="none",
    task_type=TaskType.CAUSAL_LM # Modelin türü (Metin üretimi)
)

# Ayarları modele uygulama
model = get_peft_model(model, peft_config)

# Ne kadar parametre eğiteceğimizi görelim
print("Eğitilecek parametre tablosu:")
model.print_trainable_parameters()

from transformers import TrainingArguments
from trl import SFTTrainer
from transformers import DataCollatorForLanguageModeling

# Kodun geri kalanında 'eval_dataset' kullanıldığı için val_dataset'i atıyoruz
eval_dataset = val_dataset

model.gradient_checkpointing_enable()
model.config.use_cache = False

training_args = TrainingArguments(
    output_dir="qwen25_coder_15b_l4",

    num_train_epochs=3,

    per_device_train_batch_size=2,
    gradient_accumulation_steps=8,   # efektif batch = 16

    learning_rate=4e-4,
    warmup_ratio=0.03,

    fp16=False,
    bf16=True,

    optim="adamw_torch_fused",
    weight_decay=0.01,
    max_grad_norm=0.3,

    save_strategy="steps",
    save_steps=100,
    logging_steps=20,

    eval_strategy="steps",
    eval_steps=100,
    # eval_dataset parametresi buradan kaldırıldı. Trainer'a verilecek.

    load_best_model_at_end=False,
    lr_scheduler_type="cosine",

    report_to="tensorboard",
)

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False,
)

tokenizer.model_max_length = 1024

def tokenize_fn(example):
    return tokenizer(
        example["text"],
        truncation=True,
        max_length=1024,
        padding=False,
    )

# Check if 'text' column exists before mapping to avoid KeyError on re-run
if "text" in train_dataset.column_names:
    print("Tokenizing train dataset...")
    train_dataset = train_dataset.map(
        tokenize_fn,
        batched=True,
        remove_columns=train_dataset.column_names,
    )
else:
    print("Train dataset already tokenized.")

if "text" in eval_dataset.column_names:
    print("Tokenizing eval dataset...")
    eval_dataset = eval_dataset.map(
        tokenize_fn,
        batched=True,
        remove_columns=eval_dataset.column_names,
    )
else:
    print("Eval dataset already tokenized.")


# Trainer'a eval dataseti de veriyoruz
trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    peft_config=peft_config,
    data_collator=data_collator,
)

# Gradient checkpointing kullanıldığı için input embedding'lerin gradyan gerektirdiğini belirtmeliyiz.
# Bu işlem yapılmazsa "element 0 of tensors does not require grad" hatası alınır.
if hasattr(model, "enable_input_require_grads"):
    model.enable_input_require_grads()

trainer.train()

import os
import gc
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, Trainer, DataCollatorForLanguageModeling

# ----------------------------------------
# GPU / VRAM TEMİZLİK (TRAINING SONRASI)
# ----------------------------------------

def clear_vram():
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        torch.cuda.ipc_collect()

print("🧹 Training sonrası VRAM temizleniyor...")
clear_vram()

# ----------------------------------------
# Ayarlar
# ----------------------------------------

# EĞİTİMDEKİ output_dir İLE AYNI OLMALI
output_dir = "qwen25_coder_15b_l4"
device = "cuda" if torch.cuda.is_available() else "cpu"

best_checkpoint = None
best_test_loss = float("inf")

# ----------------------------------------
# Tokenizer (tek sefer)
# ----------------------------------------

# Tokenizer eğitim çıktısında yoksa, orijinal modelden yüklenir
try:
    tokenizer = AutoTokenizer.from_pretrained(output_dir)
except:
    print(f"{output_dir} içinde tokenizer bulunamadı, orijinal modelden yükleniyor...")
    tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen2.5-Coder-1.5B-Instruct")

tokenizer.pad_token = tokenizer.eos_token

# ----------------------------------------
# Test Verisini Tokenize Et
# ----------------------------------------

def tokenize_fn(example):
    return tokenizer(
        example["text"],
        truncation=True,
        max_length=1024,
        padding=False,
    )

# test_dataset globalden geliyor, tokenize edilmemiş olabilir.
if "input_ids" not in test_dataset.column_names:
    print("Test verisi tokenize ediliyor...")
    test_dataset = test_dataset.map(
        tokenize_fn,
        batched=True,
        remove_columns=test_dataset.column_names
    )
else:
    print("Test verisi zaten tokenize edilmiş.")

# ----------------------------------------
# Checkpoint'leri Bul
# ----------------------------------------

if not os.path.exists(output_dir):
    print(f"HATA: {output_dir} klasörü bulunamadı. Lütfen eğitimin tamamlandığından emin olun.")
    checkpoints = []
else:
    checkpoints = sorted(
        [
            os.path.join(output_dir, d)
            for d in os.listdir(output_dir)
            if d.startswith("checkpoint-")
        ],
        key=lambda x: int(x.split("-")[-1])
    )

print(f"Bulunan checkpoint sayısı: {len(checkpoints)}")

# ----------------------------------------
# CHECKPOINT → TEST EVAL LOOP (VRAM SAFE)
# ----------------------------------------

for ckpt in checkpoints:
    print(f"\n🔍 Test ediliyor: {ckpt}")

    clear_vram()  # güvenlik amaçlı, yüklemeden önce

    model = AutoModelForCausalLM.from_pretrained(
        ckpt,
        torch_dtype=torch.float16,
        device_map="auto",
        low_cpu_mem_usage=True
    )

    # Loss hesabı için data_collator gerekli (Labels oluşturur)
    data_collator = DataCollatorForLanguageModeling(tokenizer, mlm=False)

    trainer = Trainer(
        model=model,
        tokenizer=tokenizer,
        eval_dataset=test_dataset,
        data_collator=data_collator
    )

    with torch.no_grad():
        metrics = trainer.evaluate()

    if "eval_loss" in metrics:
        test_loss = metrics["eval_loss"]
        print(f"📉 Test Loss: {test_loss}")

        if test_loss < best_test_loss:
            best_test_loss = test_loss
            best_checkpoint = ckpt
    else:
        print("⚠️ Eval loss hesaplanamadı. (Metrics içinde 'eval_loss' yok)")
        print("Metrics:", metrics)

    # ---- VRAM TEMİZLİĞİ (EN ÖNEMLİ KISIM) ----
    del trainer
    del model
    clear_vram()

# ----------------------------------------
# SONUÇ
# ----------------------------------------

if best_checkpoint:
    print("\n🏆 FINAL CHECKPOINT SEÇİLDİ")
    print(f"Checkpoint: {best_checkpoint}")
    print(f"En İyi Test Loss: {best_test_loss}")
else:
    print("\n⚠️ Hiçbir checkpoint test edilemedi.")

# ===============================
# CELL 1: TRAIN / VAL LOG KAYDI
# ===============================

import os
import json
import shutil

# ---- Ayarlar ----
LOCAL_LOG_DIR = "logs"
DRIVE_LOG_DIR = "/content/drive/MyDrive/qwen_logs"
OUTPUT_DIR = "qwen25_coder_15b_l4"

os.makedirs(LOCAL_LOG_DIR, exist_ok=True)

# ---- Log Geçmişini Dosyadan Okuma ----
# Trainer nesnesi silindiği için logs verisini son checkpoint'teki dosyadan okuyoruz.
log_history = []
try:
    if os.path.exists(OUTPUT_DIR):
        checkpoints = sorted(
            [d for d in os.listdir(OUTPUT_DIR) if d.startswith("checkpoint-")],
            key=lambda x: int(x.split("-")[-1])
        )

        if checkpoints:
            last_ckpt = checkpoints[-1]
            state_path = os.path.join(OUTPUT_DIR, last_ckpt, "trainer_state.json")

            if os.path.exists(state_path):
                with open(state_path, "r") as f:
                    state_data = json.load(f)
                log_history = state_data.get("log_history", [])
                print(f"✅ Log geçmişi {state_path} dosyasından okundu.")
            else:
                print("⚠️ trainer_state.json bulunamadı.")
        else:
            print("⚠️ Hiçbir checkpoint bulunamadı.")
    else:
        print(f"⚠️ {OUTPUT_DIR} klasörü bulunamadı.")
except Exception as e:
    print(f"⚠️ Log okuma hatası: {e}")

# ---- JSON Olarak Kaydetme ----
train_val_log_path = f"{LOCAL_LOG_DIR}/training_validation_logs.json"

with open(train_val_log_path, "w") as f:
    json.dump(log_history, f, indent=2)

print(f"✅ Training + Validation logları kaydedildi: {train_val_log_path}")

# ---- Google Drive'a kopyala (Colab ise) ----
try:
    from google.colab import drive
    if not os.path.exists("/content/drive"):
        drive.mount("/content/drive")

    os.makedirs(DRIVE_LOG_DIR, exist_ok=True)
    shutil.copy(train_val_log_path, DRIVE_LOG_DIR)

    print(f"☁️ Drive'a kopyalandı: {DRIVE_LOG_DIR}")
except:
    print("ℹ️ Drive ortamı yok veya erişilemedi, atlandı.")

# =====================================================
# CELL 2: CHECKPOINT TEST + JSON + GRAFİK + DOWNLOAD
# =====================================================

import os
import gc
import json
import torch
import shutil
import matplotlib.pyplot as plt
from transformers import AutoModelForCausalLM, AutoTokenizer, Trainer, DataCollatorForLanguageModeling

# ---------- AYARLAR ----------
OUTPUT_DIR = "qwen25_coder_15b_l4"
LOCAL_LOG_DIR = "logs"
DRIVE_LOG_DIR = "/content/drive/MyDrive/qwen_logs"

os.makedirs(LOCAL_LOG_DIR, exist_ok=True)

def clear_vram():
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        torch.cuda.ipc_collect()

# ---------- CHECKPOINT BUL ----------
checkpoints = sorted(
    [os.path.join(OUTPUT_DIR, d) for d in os.listdir(OUTPUT_DIR) if d.startswith("checkpoint-")],
    key=lambda x: int(x.split("-")[-1])
)

# Tokenizer yükleme (Hata önleyici fallback yapısı)
try:
    tokenizer = AutoTokenizer.from_pretrained(OUTPUT_DIR)
except:
    print(f"{OUTPUT_DIR} içinde tokenizer bulunamadı, orijinal modelden yükleniyor...")
    tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen2.5-Coder-1.5B-Instruct")

tokenizer.pad_token = tokenizer.eos_token

test_results = []
best_ckpt, best_loss = None, float("inf")

clear_vram()

# ---------- TEST LOOP ----------
for ckpt in checkpoints:
    print(f"🔍 Test ediliyor: {ckpt}")
    clear_vram()

    model = AutoModelForCausalLM.from_pretrained(
        ckpt,
        torch_dtype=torch.bfloat16,
        device_map="auto",
        low_cpu_mem_usage=True
    )

    # Loss hesabı için gerekli
    data_collator = DataCollatorForLanguageModeling(tokenizer, mlm=False)

    trainer = Trainer(
        model=model,
        tokenizer=tokenizer,
        eval_dataset=test_dataset,
        data_collator=data_collator
    )

    with torch.no_grad():
        metrics = trainer.evaluate()

    # Eğer loss varsa al, yoksa uyarı ver
    if "eval_loss" in metrics:
        loss = metrics["eval_loss"]
    else:
        loss = float("inf")
        print(f"⚠️ {ckpt} için eval_loss hesaplanamadı!")

    test_results.append({
        "checkpoint": ckpt,
        "step": int(ckpt.split("-")[-1]),
        "test_loss": loss
    })

    if loss < best_loss:
        best_loss = loss
        best_ckpt = ckpt

    del model, trainer
    clear_vram()

# ---------- JSON KAYIT ----------
test_log_path = f"{LOCAL_LOG_DIR}/test_checkpoint_results.json"
with open(test_log_path, "w") as f:
    json.dump(test_results, f, indent=2)

print(f"\n🏆 FINAL CHECKPOINT: {best_ckpt}")
print(f"📉 En iyi Test Loss: {best_loss}")
print(f"✅ Test logları kaydedildi: {test_log_path}")

# ---------- GRAFİKLER ----------
with open(f"{LOCAL_LOG_DIR}/training_validation_logs.json") as f:
    logs = json.load(f)

train_s, train_l, eval_s, eval_l = [], [], [], []
for x in logs:
    if "loss" in x:
        train_s.append(x["step"])
        train_l.append(x["loss"])
    if "eval_loss" in x:
        eval_s.append(x["step"])
        eval_l.append(x["eval_loss"])

plt.figure()
plt.plot(train_s, train_l, label="Train")
plt.plot(eval_s, eval_l, label="Validation")
plt.legend()
plt.title("Train / Validation Loss")
plt.show()

steps = [x["step"] for x in test_results]
losses = [x["test_loss"] for x in test_results]

# 1. Benchmark reposunu çekiyoruz
!git clone https://github.com/naholav/CodeGen.git

# 2. Gerekli kütüphaneleri kuruyoruz
!pip install -r CodeGen/requirements.txt

import os
import shutil
import json
import math

# --- AYARLAR ---
# Senin eğitimin çıktığı klasör
source_dir = "./qwen25_coder_15b_l4"

# PDF'teki hedef klasör (Hangi eğitimi yapıyorsan ismini ona göre düzelt: 'deep' veya 'diverse')
target_base = "./CodeGen/models/deep_instruction/checkpoints"

print(f"📂 Dosyalar '{source_dir}' kaynağından '{target_base}' hedefine taşınıyor...\n")

if not os.path.exists(target_base):
    os.makedirs(target_base)

# Checkpointleri bul
for folder_name in os.listdir(source_dir):
    if "checkpoint-" in folder_name:
        src_path = os.path.join(source_dir, folder_name)

        # 1. trainer_state.json dosyasını bul ve oku
        json_path = os.path.join(src_path, "trainer_state.json")

        real_epoch = 1 # Varsayılan değer (dosya bulunamazsa)

        if os.path.exists(json_path):
            with open(json_path, 'r') as f:
                data = json.load(f)
                # Epoch değerini al (örn: 2.14) ve yukarı yuvarla (örn: 3)
                # Çünkü 2.14 demek, 2 bitmiş 3. epoch'un içindeyiz demektir.
                if 'epoch' in data:
                    real_epoch = math.ceil(data['epoch'])

        # 2. Adı PDF formatına çevir
        # Format: checkpoint-step-{ADIM}-epoch-{GERÇEK_EPOCH}
        step_num = folder_name.split("-")[-1] # "checkpoint-500" -> "500"
        new_folder_name = f"checkpoint-step-{step_num}-epoch-{real_epoch}"

        dest_path = os.path.join(target_base, new_folder_name)

        # 3. Kopyalama işlemi
        if os.path.exists(src_path):
             # Eğer hedefte zaten varsa hata vermemesi için dirs_exist_ok=True
             shutil.copytree(src_path, dest_path, dirs_exist_ok=True)
             print(f"✅ İşlendi: {folder_name} -> {new_folder_name} (Epoch verisi json'dan okundu)")

print("\n🏁 Klasör düzeni ve isimlendirme tamamlandı!")

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/CodeGen
!pip install flash-attn --no-build-isolation
!python livecodebench_eval.py \
  --model_type deep_instruction \
  --platform atcoder \
  --difficulty easy

!python livecodebench_eval.py --include_base --platform atcoder --difficulty easy